config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users, path: ''
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root to: 'articles#index'

  get '/my_articles', to: 'articles#my_articles'
  get '/articles_without_datatable', to: 'articles#articles_without_datatable'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :programming_language_id, presence: true

  belongs_to :user
  belongs_to :programming_language

  scope :search_by_title_and_programming_language, ->(query_string) { 
    joins(:programming_language).where("articles.title LIKE :search_query OR programming_languages.name LIKE :search_query", search_query: query_string)
  }
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
      validates :name, presence: true
      has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    articles_path
  end

  def after_sign_out_path_for(resource_or_scope)
    articles_path
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    @title = "All Articles"
    respond_to do |format|
      format.json { render json: ArticleDatatable.new(view_context) }
      format.html
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
      unless is_owner? @article
        redirect_to @article, alert: 'Action unsuccessful, you are not the owner.'
      end
  end

  # POST /articles
  # POST /articles.json
  def create
    data = article_params.merge({user_id: current_user.id})
    @article = Article.new(data)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|

      unless is_owner? @article
        format.html { redirect_to @article, alert: 'Action unsuccessful, you are not the owner.'}
        format.json { render :show, status: :error, message: :not_owner }
      else
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    respond_to do |format|

      unless is_owner? @article
        format.html { redirect_to articles_url, alert: 'Action unsuccessful, you are not the owner.'}
        format.json { render :show, status: :error, message: :not_owner }
      else
        @article.destroy
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def my_articles
    @title = "My Articles"    
    respond_to do |format|
      Article.find_by(user_id: current_user.id)
      format.html {render 'articles/index' }
      format.json { render json: ArticleDatatable.new(view_context, { user: current_user }) }
    end 
  end

  def articles_without_datatable
    @articles = Article.order(id: :desc)

    unless params[:search].blank?
      @articles = @articles.search_by_title_and_programming_language("%#{params[:search]}%")
    end

    @articles = @articles.page(params[:page]).per(1)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :programming_language_id)
    end

    def require_permission
      if current_user != Article.find(params[:id]).user
        redirect_to article_path
      end
    end

    def is_owner? article
      current_user == article.user ? true : false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def body_class
        [controller_name, action_name].join('-')
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_actions.html.erb
<%=
  link_to('Show', article) + ' ' +
  (
    (
      link_to('Edit', edit_article_path(article)) + ' ' + 
      link_to('Destroy', article, method: :delete, data: { confirm: 'Are you sure?' })
    ) if user_signed_in?
  )
%>

app/views/articles/_footer_buttons.html.erb
<div class="message">
  <%=
  link_to('All Articles', articles_path, class: 'link-button') + ' ' +  
  link_to('Articles withoud Datatable', articles_without_datatable_path, class: 'link-button') + ' ' +  
  (
    if user_signed_in?
    link_to('My Articles', my_articles_path, class: 'link-button') + ' ' +
    link_to('New Article', new_article_path, class: 'link-button')  + ' ' +
    link_to("Logout #{current_user.email}", destroy_user_session_path, class: 'link-button', method: :delete)
    else
    link_to('Login', new_user_session_path, class: 'link-button')
    end
  )
  %>
</div>

app/views/articles/_form.html.erb
<div class="edit-page">
  <h2><%= yield :title%></h2>
  <div class="form ck-form">
    <%= form_with(model: article, local: true) do |form| %>
      <% if article.errors.any? %>
        <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <div class="alert alert-alert">
        <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
      <%= form.label :title %>
      <%= form.text_field :title, id: :article_title, placeholder: "Title" %>
      <%= form.label :content %>
      <%#<%= form.text_area :content, id: :article_content, placeholder: "Content" %>
      <%= cktext_area :article, :content, cols: 40, ckeditor: { uiColor: '#ffffff', toolbar: 'mini' } %>
      <%= form.label :programming_language %>      
      <%= form.collection_select :programming_language_id, ProgrammingLanguage.all, :id, :name, {}%>
      <%= form.submit %>
      <p class="message"><%= yield :links %></p>
    <% end %>
  </div>
</div>

app/views/articles/articles_without_datatable.html.erb
<div id="demo">
  <h2>Articles</h2>
  
  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <form action=''>
    <input type="text" name="search" placeholder="Search.." class="search" />
  </form>
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Programming Language</th>
        <th>Creator</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% if @articles %>
      <% @articles.each do |article| %>
          <tr>
            <td><%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= article.programming_language.name %></td>
            <td><%= article.user.email %></td>
            <td>
              <%= render 'actions', {article: article} %>
            </td>
          </tr>
      <% end %>
    <% else %>
        <%= raw("<tr><td>No records found</td></tr>")%>
    <% end %>
    </tbody>
    </table>
  </div>
</div>
<div class="footer-articles-container">
    <div class="pagination-wrapper">    
        <%= paginate @articles %>
    </div>
    <%= render 'footer_buttons' %>
</div>

app/views/articles/edit.html.erb
<% content_for :links do %>
    <%= link_to 'Show', @article %> |
    <%= link_to 'Back', articles_path %>
<% end %>

<% content_for :title, "Edit Article" %>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="articles-page">
  <div class="articles-container">
    <h1><%= @title %></h1>
    <table id="articles-table", data-source="<%= url_for(format: :json) %>">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Programming Language</th>
          <th>Creator</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
    <%= render 'footer_buttons' %>
  </div>
</div>

app/views/articles/new.html.erb
<% content_for :links do %>
    <%= link_to 'Back', articles_path %>
<% end %>

<% content_for :title, "New Article" %>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="show-page">
  <div class="articles-container text-left">
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= raw @article.content %>
  </p>
  <p>
    <strong>Programming Language:</strong>
    <%= @article.programming_language.name %>
  </p>
  <p>
    <strong>Creator:</strong>
    <%= @article.user.email %>
  </p>
  <div class="message">
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Articles', articles_path %>
  </div>
</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <ul>
    <li>
        <%= value %>
    </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai-sublime.min.css', 'data-turbolinks-track': 'reload'  %>
    
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.min.js', integrity: 'sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=', crossorigin: 'anonymous' %>  
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="<%= body_class %>">
    <%= render 'layouts/messages' %>
    <%= yield %>

    <%= javascript_include_tag 'https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js' %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js", 'data-turbolinks-track': 'reload'  %>
    
    <script>hljs.initHighlightingOnLoad();</script>

  </body>
</html>